// 203 client-side mini AI tools. Each: { id, name, emoji, cat, desc, gen?, placeholder?, run(input)->string }
// Rendered by tool.html and listed in the AI Zone. All run in the browser.
const MORSE={A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..','0':'-----','1':'.----','2':'..---','3':'...--','4':'....-','5':'.....','6':'-....','7':'--...','8':'---..','9':'----.','.':'.-.-.-',',':'--..--','?':'..--..','!':'-.-.--','/':'-..-.','-':'-....-','@':'.--.-.'};
const MORSE_REV=Object.fromEntries(Object.entries(MORSE).map(([k,v])=>[v,k]));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const words=s=>(s.match(/[A-Za-z0-9]+/g)||[]);
function b64enc(s){ try{ return btoa(unescape(encodeURIComponent(s))); }catch(e){ return 'Could not encode'; } }
function b64dec(s){ try{ return decodeURIComponent(escape(atob(s.trim()))); }catch(e){ return 'Invalid Base64'; } }
function toRoman(x){ let n=parseInt(x,10); if(isNaN(n)||n<1||n>3999) return 'Enter a whole number 1–3999'; const m=[['M',1000],['CM',900],['D',500],['CD',400],['C',100],['XC',90],['L',50],['XL',40],['X',10],['IX',9],['V',5],['IV',4],['I',1]]; let r=''; for(const [s,v] of m){ while(n>=v){ r+=s; n-=v; } } return r; }
function numWords(x){ let num=parseInt(x,10); if(isNaN(num)) return 'Enter a whole number'; if(num===0) return 'zero'; if(Math.abs(num)>999999999999) return 'Too big!'; const o=['','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'],t=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety']; const ch=n=>{ let s=''; if(n>=100){ s+=o[Math.floor(n/100)]+' hundred'; n%=100; if(n)s+=' '; } if(n>=20){ s+=t[Math.floor(n/10)]; n%=10; if(n)s+='-'+o[n]; } else if(n>0) s+=o[n]; return s; }; let neg=num<0; num=Math.abs(num); const sc=['','thousand','million','billion']; let p=[],i=0; while(num>0){ const c=num%1000; if(c)p.unshift(ch(c)+(sc[i]?' '+sc[i]:'')); num=Math.floor(num/1000); i++; } return (neg?'negative ':'')+p.join(' '); }

// ---- helpers for the extra 50 tools ----
const nums=s=>(s.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);
function fancyMap(s,U,L,D){ return Array.from(s).map(ch=>{ const c=ch.codePointAt(0); if(U&&c>=65&&c<=90)return String.fromCodePoint(U+c-65); if(L&&c>=97&&c<=122)return String.fromCodePoint(L+c-97); if(D&&c>=48&&c<=57)return String.fromCodePoint(D+c-48); return ch; }).join(''); }
const NATO={A:'Alpha',B:'Bravo',C:'Charlie',D:'Delta',E:'Echo',F:'Foxtrot',G:'Golf',H:'Hotel',I:'India',J:'Juliett',K:'Kilo',L:'Lima',M:'Mike',N:'November',O:'Oscar',P:'Papa',Q:'Quebec',R:'Romeo',S:'Sierra',T:'Tango',U:'Uniform',V:'Victor',W:'Whiskey',X:'X-ray',Y:'Yankee',Z:'Zulu','0':'Zero','1':'One','2':'Two','3':'Three','4':'Four','5':'Five','6':'Six','7':'Seven','8':'Eight','9':'Nine'};
const SMALLCAPS={a:'ᴀ',b:'ʙ',c:'ᴄ',d:'ᴅ',e:'ᴇ',f:'ꜰ',g:'ɢ',h:'ʜ',i:'ɪ',j:'ᴊ',k:'ᴋ',l:'ʟ',m:'ᴍ',n:'ɴ',o:'ᴏ',p:'ᴘ',q:'ꞯ',r:'ʀ',s:'ꜱ',t:'ᴛ',u:'ᴜ',v:'ᴠ',w:'ᴡ',x:'x',y:'ʏ',z:'ᴢ'};
const SUPER={a:'ᵃ',b:'ᵇ',c:'ᶜ',d:'ᵈ',e:'ᵉ',f:'ᶠ',g:'ᵍ',h:'ʰ',i:'ⁱ',j:'ʲ',k:'ᵏ',l:'ˡ',m:'ᵐ',n:'ⁿ',o:'ᵒ',p:'ᵖ',q:'q',r:'ʳ',s:'ˢ',t:'ᵗ',u:'ᵘ',v:'ᵛ',w:'ʷ',x:'ˣ',y:'ʸ',z:'ᶻ','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};
const FLIP=(()=>{ const n='abcdefghijklmnopqrstuvwxyz0123456789', f='ɐqɔpǝɟƃɥıɾʞlɯuodbɹsʇnʌʍxʎz0ƖᄅƐㄣϛ9ㄥ86', m={}; for(let i=0;i<n.length;i++) m[n[i]]=f[i]; return m; })();
function pigWord(w){ const m=w.match(/^([^a-zA-Z]*)([a-zA-Z]+)([^a-zA-Z]*)$/); if(!m) return w; const lead=m[1], core=m[2], tail=m[3]; if(/^[aeiouAEIOU]/.test(core)) return lead+core+'way'+tail; const c=core.match(/^[^aeiouAEIOU]+/)[0]; return lead+core.slice(c.length)+c.toLowerCase()+'ay'+tail; }
function hexToRgb(h){ const m=(h||'').trim().replace(/^#/,'').match(/^([0-9a-f]{3}|[0-9a-f]{6})$/i); if(!m) return null; let x=m[1]; if(x.length===3) x=x.split('').map(c=>c+c).join(''); return [parseInt(x.slice(0,2),16),parseInt(x.slice(2,4),16),parseInt(x.slice(4,6),16)]; }
const toHex2=n=>Math.max(0,Math.min(255,Math.round(n))).toString(16).padStart(2,'0');
function parseDate(s){ s=(s||'').trim(); const m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/); const d=m?new Date(+m[1],+m[2]-1,+m[3]):new Date(s); return isNaN(d)?null:d; }
const LOREM='lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo consequat duis aute irure in reprehenderit voluptate velit esse cillum eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est laborum'.split(' ');
function randHex(){ return '#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0').toUpperCase(); }
// ---- helpers for the +25 tools ----
const B32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32enc(s){ const b=[]; for(const ch of unescape(encodeURIComponent(s))) b.push(ch.charCodeAt(0)); let bits='',out=''; for(const x of b) bits+=x.toString(2).padStart(8,'0'); for(let i=0;i<bits.length;i+=5){ let ch=bits.slice(i,i+5); if(ch.length<5) ch=ch.padEnd(5,'0'); out+=B32[parseInt(ch,2)]; } while(out.length%8) out+='='; return out; }
const ZALGO_UP=[0x030d,0x030e,0x0304,0x0305,0x033f,0x0311,0x0306,0x0310,0x0352,0x0357,0x0343,0x0344,0x034a,0x034b,0x0303,0x0302,0x035b,0x0341];
const ZALGO_DN=[0x0316,0x0317,0x0318,0x0319,0x031c,0x031d,0x031e,0x0323,0x0324,0x0325,0x0326,0x0329,0x032a,0x032b,0x032c,0x0330,0x0331,0x0332];
function zalgo(s){ return Array.from(s).map(ch=>{ if(/\s/.test(ch)) return ch; let o=ch; const n=2+Math.floor(Math.random()*4); for(let i=0;i<n;i++){ const pool=Math.random()<.5?ZALGO_UP:ZALGO_DN; o+=String.fromCodePoint(pool[Math.floor(Math.random()*pool.length)]); } return o; }).join(''); }
function relLum(r,g,b){ const a=[r,g,b].map(v=>{ v/=255; return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4); }); return 0.2126*a[0]+0.7152*a[1]+0.0722*a[2]; }
function hslToRgb(h,s,l){ h=((h%360)+360)%360; s/=100; l/=100; const c=(1-Math.abs(2*l-1))*s, x=c*(1-Math.abs((h/60)%2-1)), m=l-c/2; let r,g,b; if(h<60)[r,g,b]=[c,x,0]; else if(h<120)[r,g,b]=[x,c,0]; else if(h<180)[r,g,b]=[0,c,x]; else if(h<240)[r,g,b]=[0,x,c]; else if(h<300)[r,g,b]=[x,0,c]; else [r,g,b]=[c,0,x]; return [(r+m)*255,(g+m)*255,(b+m)*255]; }
// ---- helpers for the +25 tools (to 150) ----
function rgbToHsl(r,g,b){ r/=255;g/=255;b/=255; const mx=Math.max(r,g,b),mn=Math.min(r,g,b); let h,s,l=(mx+mn)/2; if(mx===mn){h=s=0;} else { const d=mx-mn; s=l>0.5?d/(2-mx-mn):d/(mx+mn); switch(mx){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4;} h/=6; } return [Math.round(h*360),Math.round(s*100),Math.round(l*100)]; }
function zodiac(m,d){ const z=[[1,20,'Capricorn ♑'],[2,19,'Aquarius ♒'],[3,21,'Pisces ♓'],[4,20,'Aries ♈'],[5,21,'Taurus ♉'],[6,21,'Gemini ♊'],[7,23,'Cancer ♋'],[8,23,'Leo ♌'],[9,23,'Virgo ♍'],[10,23,'Libra ♎'],[11,22,'Scorpio ♏'],[12,22,'Sagittarius ♐'],[12,31,'Capricorn ♑']]; for(const e of z){ if(m<e[0]||(m===e[0]&&d<=e[1])) return e[2]; } return 'Capricorn ♑'; }

export const TOOLS = [
  // ---- Text (15) ----
  { id:'word-counter', name:'Word Counter', emoji:'🔢', cat:'Text', desc:'Count words, characters, sentences and lines.', run:s=>{ const w=(s.trim().match(/\S+/g)||[]).length; const c=s.length; const cn=s.replace(/\s/g,'').length; const se=(s.match(/[.!?]+/g)||[]).length; const ln=s?s.split(/\n/).length:0; return `Words: ${w}\nCharacters: ${c}\nCharacters (no spaces): ${cn}\nSentences: ${se}\nLines: ${ln}`; } },
  { id:'character-counter', name:'Character Counter', emoji:'🔡', cat:'Text', desc:'Count characters with and without spaces.', run:s=>`With spaces: ${s.length}\nWithout spaces: ${s.replace(/\s/g,'').length}` },
  { id:'uppercase', name:'UPPERCASE', emoji:'🔠', cat:'Text', desc:'Convert text to UPPERCASE.', run:s=>s.toUpperCase() },
  { id:'lowercase', name:'lowercase', emoji:'🔟', cat:'Text', desc:'Convert text to lowercase.', run:s=>s.toLowerCase() },
  { id:'title-case', name:'Title Case', emoji:'🆎', cat:'Text', desc:'Capitalize The First Letter Of Each Word.', run:s=>s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()) },
  { id:'sentence-case', name:'Sentence case', emoji:'✍️', cat:'Text', desc:'Capitalize the first letter of each sentence.', run:s=>s.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,c=>c.toUpperCase()) },
  { id:'reverse-text', name:'Reverse Text', emoji:'🔄', cat:'Text', desc:'Reverse your text character by character.', run:s=>s.split('').reverse().join('') },
  { id:'reverse-words', name:'Reverse Word Order', emoji:'↩️', cat:'Text', desc:'Flip the order of the words.', run:s=>s.trim().split(/\s+/).reverse().join(' ') },
  { id:'remove-spaces', name:'Remove Extra Spaces', emoji:'🧹', cat:'Text', desc:'Collapse multiple spaces and trim.', run:s=>s.replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').trim() },
  { id:'remove-breaks', name:'Remove Line Breaks', emoji:'📏', cat:'Text', desc:'Turn line breaks into spaces.', run:s=>s.replace(/\s*\n\s*/g,' ').trim() },
  { id:'sort-lines', name:'Sort Lines A→Z', emoji:'🔤', cat:'Text', desc:'Sort each line alphabetically.', run:s=>s.split('\n').sort((a,b)=>a.localeCompare(b)).join('\n') },
  { id:'dedupe-lines', name:'Remove Duplicate Lines', emoji:'🗑️', cat:'Text', desc:'Keep only the first of each repeated line.', run:s=>[...new Set(s.split('\n'))].join('\n') },
  { id:'shuffle-lines', name:'Shuffle Lines', emoji:'🎴', cat:'Text', desc:'Randomly reorder the lines.', run:s=>{ const a=s.split('\n'); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a.join('\n'); } },
  { id:'number-lines', name:'Number the Lines', emoji:'🔢', cat:'Text', desc:'Add 1., 2., 3. before each line.', run:s=>s.split('\n').map((l,i)=>`${i+1}. ${l}`).join('\n') },
  { id:'count-vowels', name:'Count Vowels', emoji:'🅰️', cat:'Text', desc:'Count vowels and consonants.', run:s=>{ const v=(s.match(/[aeiou]/gi)||[]).length; const c=(s.match(/[bcdfghjklmnpqrstvwxyz]/gi)||[]).length; return `Vowels: ${v}\nConsonants: ${c}`; } },

  // ---- Format (10) ----
  { id:'slugify', name:'Slugify (URL)', emoji:'🔗', cat:'Format', desc:'Make a clean url-slug.', run:s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'') },
  { id:'snake-case', name:'snake_case', emoji:'🐍', cat:'Format', desc:'convert_text_like_this.', run:s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'') },
  { id:'kebab-case', name:'kebab-case', emoji:'🍢', cat:'Format', desc:'convert-text-like-this.', run:s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'') },
  { id:'camel-case', name:'camelCase', emoji:'🐫', cat:'Format', desc:'convertTextLikeThis.', run:s=>{ const w=words(s); return w.map((x,i)=>i?x[0].toUpperCase()+x.slice(1).toLowerCase():x.toLowerCase()).join(''); } },
  { id:'constant-case', name:'CONSTANT_CASE', emoji:'🧱', cat:'Format', desc:'CONVERT_TEXT_LIKE_THIS.', run:s=>words(s).join('_').toUpperCase() },
  { id:'capitalize-first', name:'Capitalize First Letter', emoji:'⬆️', cat:'Format', desc:'Capitalize only the first letter.', run:s=>s.charAt(0).toUpperCase()+s.slice(1) },
  { id:'strikethrough', name:'S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶', emoji:'✂️', cat:'Format', desc:'Add strike-through to your text.', run:s=>s.split('').map(c=>c+'̶').join('') },
  { id:'bubble-text', name:'Ⓑⓤⓑⓑⓛⓔ Text', emoji:'🫧', cat:'Format', desc:'Turn text into bubble letters.', run:s=>s.replace(/[a-z]/g,c=>String.fromCodePoint(0x24D0+c.charCodeAt(0)-97)).replace(/[A-Z]/g,c=>String.fromCodePoint(0x24B6+c.charCodeAt(0)-65)).replace(/[1-9]/g,c=>String.fromCodePoint(0x2460+ +c-1)).replace(/0/g,'⓪') },
  { id:'wide-text', name:'Ｗｉｄｅ Text', emoji:'🌐', cat:'Format', desc:'Aesthetic full-width / vaporwave text.', run:s=>s.replace(/[!-~]/g,c=>String.fromCodePoint(0xFF01+c.charCodeAt(0)-33)).replace(/ /g,'　') },
  { id:'clap-text', name:'Clap 👏 Text', emoji:'👏', cat:'Format', desc:'Put 👏 between 👏 every 👏 word.', run:s=>s.trim().split(/\s+/).join(' 👏 ') },

  // ---- Encode (12) ----
  { id:'base64-encode', name:'Base64 Encode', emoji:'🔐', cat:'Encode', desc:'Encode text to Base64.', run:b64enc },
  { id:'base64-decode', name:'Base64 Decode', emoji:'🔓', cat:'Encode', desc:'Decode Base64 back to text.', run:b64dec },
  { id:'url-encode', name:'URL Encode', emoji:'🌍', cat:'Encode', desc:'Percent-encode text for URLs.', run:s=>{ try{ return encodeURIComponent(s); }catch(e){ return 'Could not encode'; } } },
  { id:'url-decode', name:'URL Decode', emoji:'🗺️', cat:'Encode', desc:'Decode percent-encoded text.', run:s=>{ try{ return decodeURIComponent(s); }catch(e){ return 'Invalid input'; } } },
  { id:'binary-encode', name:'Text → Binary', emoji:'1️⃣', cat:'Encode', desc:'Convert text to 0s and 1s.', run:s=>s.split('').map(c=>c.charCodeAt(0).toString(2).padStart(8,'0')).join(' ') },
  { id:'binary-decode', name:'Binary → Text', emoji:'0️⃣', cat:'Encode', desc:'Convert binary back to text.', run:s=>{ try{ return s.trim().split(/\s+/).map(b=>String.fromCharCode(parseInt(b,2))).join(''); }catch(e){ return 'Invalid binary'; } } },
  { id:'morse-encode', name:'Text → Morse', emoji:'📡', cat:'Encode', desc:'Encode to Morse code.', run:s=>s.toUpperCase().split('').map(c=>c===' '?'/':(MORSE[c]||'')).filter(x=>x!=='').join(' ') },
  { id:'morse-decode', name:'Morse → Text', emoji:'📶', cat:'Encode', desc:'Decode Morse code (use / for space).', run:s=>s.trim().split(/\s+/).map(t=>t==='/'?' ':(MORSE_REV[t]||'')).join('') },
  { id:'rot13', name:'ROT13', emoji:'🔁', cat:'Encode', desc:'Classic ROT13 letter cipher.', run:s=>s.replace(/[a-z]/gi,c=>String.fromCharCode((c<='Z'?90:122)>=(c.charCodeAt(0)+13)?c.charCodeAt(0)+13:c.charCodeAt(0)-13)) },
  { id:'caesar-cipher', name:'Caesar Cipher (+3)', emoji:'🏛️', cat:'Encode', desc:'Shift each letter by 3.', run:s=>s.replace(/[a-z]/gi,c=>{ const base=c<='Z'?65:97; return String.fromCharCode((c.charCodeAt(0)-base+3)%26+base); }) },
  { id:'leetspeak', name:'L33t Speak', emoji:'👾', cat:'Encode', desc:'Convert to 1337 / leetspeak.', run:s=>s.replace(/a/gi,'4').replace(/e/gi,'3').replace(/i/gi,'1').replace(/o/gi,'0').replace(/s/gi,'5').replace(/t/gi,'7') },
  { id:'hex-encode', name:'Text → Hex', emoji:'#️⃣', cat:'Encode', desc:'Convert text to hex codes.', run:s=>s.split('').map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join(' ') },

  // ---- Calc (6) ----
  { id:'temp-converter', name:'Temperature Converter', emoji:'🌡️', cat:'Calc', desc:'Type a number; see °C and °F.', placeholder:'e.g. 100', run:s=>{ const n=parseFloat(s); if(isNaN(n)) return 'Enter a number'; return `${n}°C = ${(n*9/5+32).toFixed(2)}°F\n${n}°F = ${((n-32)*5/9).toFixed(2)}°C`; } },
  { id:'tip-calculator', name:'Tip Calculator', emoji:'🧾', cat:'Calc', desc:'Type the bill; see tip amounts.', placeholder:'e.g. 48.50', run:s=>{ const b=parseFloat(s); if(isNaN(b)) return 'Enter the bill amount'; return [10,15,18,20].map(p=>`${p}% tip: $${(b*p/100).toFixed(2)}  (total $${(b*(1+p/100)).toFixed(2)})`).join('\n'); } },
  { id:'average-calculator', name:'Average Calculator', emoji:'📊', cat:'Calc', desc:'Enter numbers; get sum, average, min, max.', placeholder:'e.g. 4, 8, 15, 16, 23', run:s=>{ const n=(s.match(/-?\d+(\.\d+)?/g)||[]).map(Number); if(!n.length) return 'Enter some numbers'; const sum=n.reduce((a,b)=>a+b,0); return `Count: ${n.length}\nSum: ${sum}\nAverage: ${(sum/n.length).toFixed(2)}\nMin: ${Math.min(...n)}\nMax: ${Math.max(...n)}`; } },
  { id:'percentage', name:'Percentage Calculator', emoji:'💯', cat:'Calc', desc:'Enter two numbers x y → x% of y & x of y.', placeholder:'e.g. 20 80', run:s=>{ const n=(s.match(/-?\d+(\.\d+)?/g)||[]).map(Number); if(n.length<2) return 'Enter two numbers, e.g. "20 80"'; const [x,y]=n; return `${x}% of ${y} = ${(x/100*y)}\n${x} is ${(y?(x/y*100).toFixed(2):'∞')}% of ${y}`; } },
  { id:'roman-numeral', name:'Roman Numerals', emoji:'🏛️', cat:'Calc', desc:'Convert a number (1–3999) to Roman.', placeholder:'e.g. 2025', run:toRoman },
  { id:'number-to-words', name:'Number to Words', emoji:'🔢', cat:'Calc', desc:'Spell a number in English.', placeholder:'e.g. 1234', run:numWords },

  // ---- Fun / Random (7) ----
  { id:'magic-8-ball', name:'Magic 8-Ball', emoji:'🎱', cat:'Fun', desc:'Ask anything — get an answer.', gen:true, run:()=>pick(['It is certain ✅','Without a doubt 💯','Yes – definitely 👍','Most likely 🙂','Ask again later 🤔','Cannot predict now 🌫️','Don’t count on it 🙅','My reply is no ❌','Very doubtful 😬','Signs point to yes ✨']) },
  { id:'dice-roller', name:'Dice Roller', emoji:'🎲', cat:'Fun', desc:'Roll two six-sided dice.', gen:true, run:()=>{ const a=1+Math.floor(Math.random()*6), b=1+Math.floor(Math.random()*6); return `🎲 ${a}  🎲 ${b}   (total ${a+b})`; } },
  { id:'coin-flip', name:'Coin Flip', emoji:'🪙', cat:'Fun', desc:'Heads or tails?', gen:true, run:()=>pick(['🪙 Heads','🪙 Tails']) },
  { id:'random-number', name:'Random Number (1–100)', emoji:'🔢', cat:'Fun', desc:'Get a random number from 1 to 100.', gen:true, run:()=>'🎯 '+(1+Math.floor(Math.random()*100)) },
  { id:'random-emoji', name:'Random Emoji', emoji:'😀', cat:'Fun', desc:'Get a handful of random emojis.', gen:true, run:()=>{ const E=['😀','😎','🥳','🐶','🐱','🦊','🍕','🌈','🚀','⭐','🎮','🎨','🐉','🦄','🍩','⚡','🌸','🎧','🏆','💎']; return Array.from({length:6},()=>pick(E)).join(' '); } },
  { id:'random-color', name:'Random Color', emoji:'🎨', cat:'Fun', desc:'Get a random hex color.', gen:true, run:()=>{ const h='#'+Math.floor(Math.random()*16777215).toString(16).padStart(6,'0').toUpperCase(); return h; } },
  { id:'affirmation', name:'Daily Affirmation', emoji:'🌟', cat:'Fun', desc:'A little boost of positivity.', gen:true, run:()=>pick(['You are capable of amazing things 💜','Every day is a fresh start 🌅','You’ve got this! 💪','Your effort matters 🌟','Be proud of how far you’ve come ✨','Mistakes help you grow 🌱','You make the world brighter 🌈']) },

  // ================= 50 MORE TOOLS =================

  // ---- Text / analysis (7) ----
  { id:'reading-time', name:'Reading Time', emoji:'⏱️', cat:'Text', desc:'Estimate how long your text takes to read.', run:s=>{ const w=(s.trim().match(/\S+/g)||[]).length; const mins=w/200; const sec=Math.round(mins*60); return `${w} words\n~${mins<1?'<1':Math.round(mins)} min read  (about ${sec}s at 200 wpm)`; } },
  { id:'word-frequency', name:'Word Frequency', emoji:'📊', cat:'Text', desc:'See your most-used words.', run:s=>{ const w=(s.toLowerCase().match(/[a-z0-9']+/g)||[]); if(!w.length) return 'Enter some text'; const f={}; w.forEach(x=>f[x]=(f[x]||0)+1); return Object.entries(f).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`${v} × ${k}`).join('\n'); } },
  { id:'longest-word', name:'Longest Word', emoji:'📏', cat:'Text', desc:'Find the longest word in your text.', run:s=>{ const w=(s.match(/[A-Za-z']+/g)||[]); if(!w.length) return 'No words found'; const l=w.reduce((a,b)=>b.length>a.length?b:a); return `“${l}” (${l.length} letters)`; } },
  { id:'pig-latin', name:'Pig Latin', emoji:'🐷', cat:'Text', desc:'Translate text into Pig Latin.', run:s=>s.replace(/\S+/g,pigWord) },
  { id:'remove-punct', name:'Remove Punctuation', emoji:'🚫', cat:'Text', desc:'Strip out all punctuation marks.', run:s=>s.replace(/[^\p{L}\p{N}\s]/gu,'') },
  { id:'strip-html', name:'Remove HTML Tags', emoji:'🧼', cat:'Text', desc:'Strip HTML tags, keep the text.', run:s=>s.replace(/<[^>]*>/g,'').replace(/[ \t]+/g,' ').trim() },
  { id:'extract-emails', name:'Extract Emails', emoji:'📧', cat:'Text', desc:'Pull every email address out of the text.', run:s=>{ const m=s.match(/[\w.+-]+@[\w-]+\.[\w.-]+/g); return m?[...new Set(m)].join('\n'):'No email addresses found'; } },

  // ---- Web / data (6) ----
  { id:'extract-urls', name:'Extract Links', emoji:'🔗', cat:'Web', desc:'Pull every URL out of the text.', run:s=>{ const m=s.match(/https?:\/\/[^\s<>"')]+/g); return m?[...new Set(m)].join('\n'):'No links found'; } },
  { id:'extract-numbers', name:'Extract Numbers', emoji:'🔢', cat:'Web', desc:'Pull all the numbers out of the text.', run:s=>{ const m=s.match(/-?\d[\d,]*(?:\.\d+)?/g); return m?m.join('\n'):'No numbers found'; } },
  { id:'extract-hashtags', name:'Extract Hashtags', emoji:'#️⃣', cat:'Web', desc:'Grab every #hashtag from the text.', run:s=>{ const m=s.match(/#[A-Za-z0-9_]+/g); return m?[...new Set(m)].join(' '):'No hashtags found'; } },
  { id:'json-format', name:'JSON Pretty Print', emoji:'🧩', cat:'Web', desc:'Format & indent messy JSON.', placeholder:'{"a":1,"b":[2,3]}', run:s=>{ try{ return JSON.stringify(JSON.parse(s),null,2); }catch(e){ return 'Invalid JSON: '+e.message; } } },
  { id:'html-encode', name:'HTML Encode', emoji:'📜', cat:'Web', desc:'Escape text for safe HTML.', run:s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;') },
  { id:'html-decode', name:'HTML Decode', emoji:'📄', cat:'Web', desc:'Turn HTML entities back into text.', run:s=>s.replace(/&#39;/g,"'").replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&') },

  // ---- Encode / cipher (6) ----
  { id:'rot47', name:'ROT47', emoji:'🔃', cat:'Encode', desc:'ROT47 cipher (letters, digits & symbols).', run:s=>s.replace(/[!-~]/g,c=>String.fromCharCode(33+(c.charCodeAt(0)-33+47)%94)) },
  { id:'atbash', name:'Atbash Cipher', emoji:'🔯', cat:'Encode', desc:'Mirror-alphabet cipher (a↔z, b↔y…).', run:s=>s.replace(/[a-z]/gi,c=>{ const base=c<='Z'?65:97; return String.fromCharCode(base+25-(c.charCodeAt(0)-base)); }) },
  { id:'nato-phonetic', name:'NATO Phonetic', emoji:'📻', cat:'Encode', desc:'Spell it out: Alpha Bravo Charlie…', run:s=>s.toUpperCase().split('').map(c=>NATO[c]||(c===' '?'/':'')).filter(Boolean).join(' ') },
  { id:'ascii-encode', name:'Text → ASCII Codes', emoji:'🔟', cat:'Encode', desc:'Character codes (decimal).', run:s=>Array.from(s).map(c=>c.codePointAt(0)).join(' ') },
  { id:'ascii-decode', name:'ASCII Codes → Text', emoji:'🔡', cat:'Encode', desc:'Turn decimal codes back into text.', placeholder:'72 105 33', run:s=>{ try{ return (s.trim().match(/\d+/g)||[]).map(n=>String.fromCodePoint(+n)).join(''); }catch(e){ return 'Invalid codes'; } } },
  { id:'unicode-escape', name:'Text → \\u Escapes', emoji:'⌨️', cat:'Encode', desc:'JavaScript-style \\uXXXX escapes.', run:s=>s.split('').map(c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')).join('') },

  // ---- Format / fancy text (10) ----
  { id:'mocking-case', name:'MoCkInG cAsE', emoji:'🧽', cat:'Format', desc:'aLtErNaTiNg SpOnGeBoB text.', run:s=>{ let i=0; return s.split('').map(ch=>{ if(/[a-z]/i.test(ch)){ const r=i%2?ch.toUpperCase():ch.toLowerCase(); i++; return r; } return ch; }).join(''); } },
  { id:'bold-unicode', name:'𝗕𝗼𝗹𝗱 Text', emoji:'🅱️', cat:'Format', desc:'Unicode bold that works anywhere.', run:s=>fancyMap(s,0x1D5D4,0x1D5EE,0x1D7EC) },
  { id:'italic-unicode', name:'𝘐𝘵𝘢𝘭𝘪𝘤 Text', emoji:'🎭', cat:'Format', desc:'Unicode italic that works anywhere.', run:s=>fancyMap(s,0x1D608,0x1D622,0) },
  { id:'script-unicode', name:'𝓒𝓾𝓻𝓼𝓲𝓿𝓮 Text', emoji:'✒️', cat:'Format', desc:'Fancy cursive / script letters.', run:s=>fancyMap(s,0x1D4D0,0x1D4EA,0) },
  { id:'monospace-unicode', name:'Ｍｏｎｏ Text', emoji:'⌗', cat:'Format', desc:'Unicode monospace letters.', run:s=>fancyMap(s,0x1D670,0x1D68A,0x1D7F6) },
  { id:'small-caps', name:'ꜱᴍᴀʟʟ ᴄᴀᴘꜱ', emoji:'🔤', cat:'Format', desc:'Turn text into tiny small-caps.', run:s=>s.toLowerCase().split('').map(c=>SMALLCAPS[c]||c).join('') },
  { id:'upside-down', name:'Upside-Down', emoji:'🙃', cat:'Format', desc:'Flip your text ┴ǝsdn.', run:s=>s.toLowerCase().split('').map(c=>FLIP[c]||c).reverse().join('') },
  { id:'superscript', name:'ˢᵘᵖᵉʳ Text', emoji:'⤴️', cat:'Format', desc:'Turn text into tiny superscript.', run:s=>s.toLowerCase().split('').map(c=>SUPER[c]||c).join('') },
  { id:'underline-text', name:'U̲n̲d̲e̲r̲l̲i̲n̲e̲', emoji:'📉', cat:'Format', desc:'Add an underline to every character.', run:s=>s.split('').map(c=>c+'̲').join('') },
  { id:'squared-text', name:'🅂🅀🅄🄰🅁🄴🄳', emoji:'🔲', cat:'Format', desc:'Boxy squared letters.', run:s=>s.toUpperCase().split('').map(c=>c>='A'&&c<='Z'?String.fromCodePoint(0x1F130+c.charCodeAt(0)-65):c).join('') },

  // ---- Calc / numbers (8) ----
  { id:'prime-check', name:'Prime Checker', emoji:'🧮', cat:'Calc', desc:'Is your number prime?', placeholder:'e.g. 97', run:s=>{ const n=parseInt(s,10); if(isNaN(n)||n<0) return 'Enter a whole number ≥ 0'; if(n<2) return `${n} is not prime`; for(let i=2;i*i<=n;i++) if(n%i===0) return `${n} is not prime (divisible by ${i})`; return `${n} is prime ✅`; } },
  { id:'factorial', name:'Factorial (n!)', emoji:'❗', cat:'Calc', desc:'Compute n! exactly.', placeholder:'e.g. 20', run:s=>{ const n=parseInt(s,10); if(isNaN(n)||n<0) return 'Enter a whole number ≥ 0'; if(n>2000) return 'Keep it ≤ 2000 please!'; let r=1n; for(let i=2n;i<=BigInt(n);i++) r*=i; return `${n}! = ${r.toString()}`; } },
  { id:'fibonacci', name:'Fibonacci Sequence', emoji:'🌀', cat:'Calc', desc:'First N Fibonacci numbers.', placeholder:'e.g. 12', run:s=>{ const n=parseInt(s,10); if(isNaN(n)||n<1) return 'Enter how many terms (≥ 1)'; if(n>200) return 'Keep it ≤ 200 terms!'; let a=0n,b=1n,out=[]; for(let i=0;i<n;i++){ out.push(a.toString()); [a,b]=[b,a+b]; } return out.join(', '); } },
  { id:'gcd-lcm', name:'GCD & LCM', emoji:'➗', cat:'Calc', desc:'Greatest common divisor & least common multiple.', placeholder:'e.g. 12 18', run:s=>{ const n=nums(s).map(x=>Math.abs(Math.round(x))).filter(x=>x>0); if(n.length<2) return 'Enter two whole numbers, e.g. "12 18"'; const g=(a,b)=>b?g(b,a%b):a; const G=n.reduce((a,b)=>g(a,b)); const L=n.reduce((a,b)=>a/g(a,b)*b); return `GCD = ${G}\nLCM = ${L}`; } },
  { id:'base-converter', name:'Number Base Converter', emoji:'🔢', cat:'Calc', desc:'Decimal → binary, octal & hex.', placeholder:'e.g. 255', run:s=>{ const n=parseInt(s,10); if(isNaN(n)) return 'Enter a whole number'; return `Binary: ${n.toString(2)}\nOctal: ${n.toString(8)}\nHex: ${n.toString(16).toUpperCase()}`; } },
  { id:'percent-change', name:'Percentage Change', emoji:'📈', cat:'Calc', desc:'From an old value to a new one.', placeholder:'old new  e.g. 80 100', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter old & new, e.g. "80 100"'; const [o,v]=n; if(o===0) return 'Old value can’t be 0'; const p=(v-o)/o*100; return `${p>=0?'+':''}${p.toFixed(2)}%  (${p>=0?'increase':'decrease'})`; } },
  { id:'discount-calc', name:'Discount Calculator', emoji:'🏷️', cat:'Calc', desc:'Price after a % off.', placeholder:'price %  e.g. 60 25', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter price & percent, e.g. "60 25"'; const [p,d]=n; const save=p*d/100; return `You save $${save.toFixed(2)}\nFinal price: $${(p-save).toFixed(2)}`; } },
  { id:'median-mode', name:'Median & Mode', emoji:'📐', cat:'Calc', desc:'Middle value and most common value.', placeholder:'e.g. 3, 5, 5, 7, 9', run:s=>{ const n=nums(s).sort((a,b)=>a-b); if(!n.length) return 'Enter some numbers'; const mid=Math.floor(n.length/2); const med=n.length%2?n[mid]:(n[mid-1]+n[mid])/2; const f={}; n.forEach(x=>f[x]=(f[x]||0)+1); const mx=Math.max(...Object.values(f)); const mode=Object.keys(f).filter(k=>f[k]===mx); return `Median: ${med}\nMode: ${mx===1?'no repeats':mode.join(', ')+' (×'+mx+')'}`; } },

  // ---- Time & date (5) ----
  { id:'days-between', name:'Days Between Dates', emoji:'📅', cat:'Time', desc:'Count the days between two dates.', placeholder:'2024-01-01 to 2025-01-01', run:s=>{ const parts=s.split(/\s+to\s+|,|\n/).map(x=>x.trim()).filter(Boolean); if(parts.length<2) return 'Enter two dates, e.g. "2024-01-01 to 2025-01-01"'; const a=parseDate(parts[0]), b=parseDate(parts[1]); if(!a||!b) return 'Couldn’t read those dates (try YYYY-MM-DD)'; const d=Math.round(Math.abs(b-a)/86400000); return `${d} day${d===1?'':'s'} apart\n(${(d/7).toFixed(1)} weeks · ${(d/365).toFixed(2)} years)`; } },
  { id:'age-calc', name:'Age Calculator', emoji:'🎂', cat:'Time', desc:'How old are you (or anything)?', placeholder:'your birthday e.g. 2000-06-15', run:s=>{ const b=parseDate(s); if(!b) return 'Enter a date, e.g. 2000-06-15'; const now=new Date(); if(b>now) return 'That date is in the future!'; let y=now.getFullYear()-b.getFullYear(), m=now.getMonth()-b.getMonth(), d=now.getDate()-b.getDate(); if(d<0){ m--; d+=new Date(now.getFullYear(),now.getMonth(),0).getDate(); } if(m<0){ y--; m+=12; } const days=Math.floor((now-b)/86400000); return `${y} years, ${m} months, ${d} days\n(that’s ${days.toLocaleString()} days!)`; } },
  { id:'countdown', name:'Countdown to Date', emoji:'⏳', cat:'Time', desc:'How long until a future date?', placeholder:'e.g. 2026-12-25', run:s=>{ const t=parseDate(s); if(!t) return 'Enter a date, e.g. 2026-12-25'; const now=new Date(); const ms=t-now; if(ms<0) return 'That date has already passed!'; const d=Math.floor(ms/86400000), h=Math.floor(ms/3600000)%24, mi=Math.floor(ms/60000)%60; return `${d} days, ${h} hours, ${mi} minutes to go! 🎉`; } },
  { id:'seconds-to-hms', name:'Seconds → H:M:S', emoji:'⏰', cat:'Time', desc:'Turn seconds into hours:minutes:seconds.', placeholder:'e.g. 3725', run:s=>{ const t=parseInt(s,10); if(isNaN(t)||t<0) return 'Enter a number of seconds'; const h=Math.floor(t/3600), m=Math.floor(t/60)%60, sec=t%60; const pad=x=>String(x).padStart(2,'0'); return `${pad(h)}:${pad(m)}:${pad(sec)}\n(${h}h ${m}m ${sec}s)`; } },
  { id:'day-of-week', name:'Day of the Week', emoji:'🗓️', cat:'Time', desc:'What weekday is any date?', placeholder:'e.g. 2026-07-04', run:s=>{ const d=parseDate(s); if(!d) return 'Enter a date, e.g. 2026-07-04'; return d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'}); } },

  // ---- Color (4) ----
  { id:'hex-to-rgb', name:'HEX → RGB', emoji:'🎨', cat:'Color', desc:'Convert a hex color to RGB.', placeholder:'#4f8cff', run:s=>{ const r=hexToRgb(s); return r?`rgb(${r[0]}, ${r[1]}, ${r[2]})`:'Enter a hex color like #4f8cff'; } },
  { id:'rgb-to-hex', name:'RGB → HEX', emoji:'🖌️', cat:'Color', desc:'Convert RGB values to a hex color.', placeholder:'79, 140, 255', run:s=>{ const n=nums(s); if(n.length<3) return 'Enter three numbers, e.g. "79, 140, 255"'; return '#'+toHex2(n[0])+toHex2(n[1])+toHex2(n[2]); } },
  { id:'complementary-color', name:'Complementary Color', emoji:'🌗', cat:'Color', desc:'Find the opposite color on the wheel.', placeholder:'#4f8cff', run:s=>{ const r=hexToRgb(s); if(!r) return 'Enter a hex color like #4f8cff'; const c='#'+toHex2(255-r[0])+toHex2(255-r[1])+toHex2(255-r[2]); return `Complement: ${c.toUpperCase()}`; } },
  { id:'random-gradient', name:'Random Gradient', emoji:'🌈', cat:'Color', desc:'Get a fresh CSS gradient.', gen:true, run:()=>{ const a=randHex(), b=randHex(), deg=Math.floor(Math.random()*360); return `${a} → ${b}\n\nbackground: linear-gradient(${deg}deg, ${a}, ${b});`; } },

  // ---- Random / generators (4) ----
  { id:'uuid-gen', name:'UUID Generator', emoji:'🆔', cat:'Random', desc:'Generate a random UUID v4.', gen:true, run:()=>{ if(typeof crypto!=='undefined'&&crypto.randomUUID) return crypto.randomUUID(); return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{ const r=Math.random()*16|0; return (c==='x'?r:(r&0x3|0x8)).toString(16); }); } },
  { id:'lorem-ipsum', name:'Lorem Ipsum', emoji:'📝', cat:'Random', desc:'Generate placeholder text (type a word count).', placeholder:'e.g. 40', run:s=>{ let n=parseInt(s,10); if(isNaN(n)||n<1) n=30; n=Math.min(n,300); let out=[]; for(let i=0;i<n;i++) out.push(pick(LOREM)); let t=out.join(' '); return t.charAt(0).toUpperCase()+t.slice(1)+'.'; } },
  { id:'team-picker', name:'Team Picker', emoji:'🧑‍🤝‍🧑', cat:'Random', desc:'Split a list into two fair teams.', placeholder:'Ava, Ben, Cara, Dan…', run:s=>{ const p=s.split(/[,\n]/).map(x=>x.trim()).filter(Boolean); if(p.length<2) return 'Enter at least two names (comma or line separated)'; for(let i=p.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [p[i],p[j]]=[p[j],p[i]]; } const h=Math.ceil(p.length/2); return `Team A: ${p.slice(0,h).join(', ')}\nTeam B: ${p.slice(h).join(', ')}`; } },
  { id:'pick-winner', name:'Pick a Winner', emoji:'🏆', cat:'Random', desc:'Randomly choose one from your list.', placeholder:'pizza, tacos, sushi…', run:s=>{ const p=s.split(/[,\n]/).map(x=>x.trim()).filter(Boolean); if(!p.length) return 'Enter some options (comma or line separated)'; return '🏆 '+pick(p); } },

  // ================= 25 MORE TOOLS (now 125) =================

  // ---- Text (5) ----
  { id:'invert-case', name:'iNVERT cASE', emoji:'🔃', cat:'Text', desc:'Swap upper and lower case.', run:s=>s.replace(/[a-z]/gi,c=>c===c.toLowerCase()?c.toUpperCase():c.toLowerCase()) },
  { id:'acronym', name:'Acronym Maker', emoji:'🔠', cat:'Text', desc:'First letter of each word → acronym.', placeholder:'e.g. National Aeronautics Space Administration', run:s=>{ const w=(s.match(/[A-Za-z0-9]+/g)||[]); return w.length?w.map(x=>x[0].toUpperCase()).join(''):'Enter some words'; } },
  { id:'initials', name:'Initials', emoji:'🅰️', cat:'Text', desc:'Turn a name into spaced initials.', placeholder:'e.g. Khyati Srivastava', run:s=>{ const w=(s.match(/[A-Za-z]+/g)||[]); return w.length?w.map(x=>x[0].toUpperCase()+'.').join(' '):'Enter a name'; } },
  { id:'repeat-text', name:'Repeat Text', emoji:'♾️', cat:'Text', desc:'Repeat text N times — "text | 3".', placeholder:'ha | 5', run:s=>{ const m=s.split('|'); const t=(m[0]||'').trim(); let n=parseInt(m[1],10); if(!t) return 'Format: text | count'; if(isNaN(n)||n<1) n=3; n=Math.min(n,1000); return Array(n).fill(t).join(' '); } },
  { id:'remove-numbers', name:'Remove Numbers', emoji:'🚯', cat:'Text', desc:'Strip out every digit.', run:s=>s.replace(/[0-9]/g,'') },

  // ---- Format (3) ----
  { id:'spaced-text', name:'S P A C E D', emoji:'📃', cat:'Format', desc:'Put a space between every letter.', run:s=>Array.from(s.replace(/\s+/g,' ')).join(' ').replace(/   /g,'  ') },
  { id:'reverse-each-word', name:'Reverse Each Word', emoji:'🔁', cat:'Format', desc:'Reverse letters, keep word order.', run:s=>s.replace(/\S+/g,w=>Array.from(w).reverse().join('')) },
  { id:'zalgo', name:'Z̸a̸l̸g̸o̸ Glitch', emoji:'👹', cat:'Format', desc:'Cursed, glitchy zalgo text.', run:s=>zalgo(s) },

  // ---- Encode (4) ----
  { id:'base32-encode', name:'Base32 Encode', emoji:'🔠', cat:'Encode', desc:'Encode text to Base32.', run:s=>s?base32enc(s):'Enter some text' },
  { id:'rot5', name:'ROT5 (digits)', emoji:'5️⃣', cat:'Encode', desc:'Shift each digit by 5.', run:s=>s.replace(/[0-9]/g,d=>String((+d+5)%10)) },
  { id:'hex-decode', name:'Hex → Text', emoji:'🔡', cat:'Encode', desc:'Decode hex codes back to text.', placeholder:'48 69 21', run:s=>{ try{ const h=s.trim().match(/[0-9a-f]{2}/gi); if(!h) return 'Enter hex like "48 69 21"'; return decodeURIComponent(h.map(x=>'%'+x).join('')); }catch(e){ return 'Invalid hex'; } } },
  { id:'html-num-entities', name:'Text → HTML Entities', emoji:'🔢', cat:'Encode', desc:'Numeric HTML entities (&#65;).', run:s=>Array.from(s).map(c=>'&#'+c.codePointAt(0)+';').join('') },

  // ---- Calc (6) ----
  { id:'quadratic', name:'Quadratic Solver', emoji:'📐', cat:'Calc', desc:'Solve ax²+bx+c=0.', placeholder:'a b c  e.g. 1 -3 2', run:s=>{ const n=nums(s); if(n.length<3) return 'Enter a, b, c — e.g. "1 -3 2"'; const [a,b,c]=n; if(a===0) return 'a can’t be 0 (not quadratic)'; const d=b*b-4*a*c; if(d<0) return `No real roots (discriminant ${d})`; const r1=(-b+Math.sqrt(d))/(2*a), r2=(-b-Math.sqrt(d))/(2*a); return d===0?`One root: x = ${r1}`:`x₁ = ${(+r1.toFixed(4))}\nx₂ = ${(+r2.toFixed(4))}`; } },
  { id:'bmi', name:'BMI Calculator', emoji:'⚖️', cat:'Calc', desc:'Body Mass Index — "kg cm".', placeholder:'weight height  e.g. 70 175', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter weight (kg) & height (cm), e.g. "70 175"'; const [w,h]=n; if(h<=0) return 'Height must be positive'; const bmi=w/Math.pow(h/100,2); const cat=bmi<18.5?'underweight':bmi<25?'healthy':bmi<30?'overweight':'obese'; return `BMI: ${bmi.toFixed(1)}\nCategory: ${cat}`; } },
  { id:'compound-interest', name:'Compound Interest', emoji:'💰', cat:'Calc', desc:'Grow money — "principal rate% years".', placeholder:'1000 5 10', run:s=>{ const n=nums(s); if(n.length<3) return 'Enter principal, rate%, years — e.g. "1000 5 10"'; const [p,r,t]=n; const amt=p*Math.pow(1+r/100,t); return `Final amount: ${amt.toFixed(2)}\nInterest earned: ${(amt-p).toFixed(2)}`; } },
  { id:'permutations', name:'nPr & nCr', emoji:'🎰', cat:'Calc', desc:'Permutations & combinations.', placeholder:'n r  e.g. 5 2', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter n and r, e.g. "5 2"'; const [N,R]=n.map(x=>Math.round(x)); if(R>N||N<0||R<0) return 'Need 0 ≤ r ≤ n'; const f=x=>{ let r=1; for(let i=2;i<=x;i++) r*=i; return r; }; const nPr=f(N)/f(N-R), nCr=nPr/f(R); return `${N}P${R} = ${nPr}\n${N}C${R} = ${nCr}`; } },
  { id:'aspect-ratio', name:'Aspect Ratio', emoji:'🖼️', cat:'Calc', desc:'Simplify width:height to a ratio.', placeholder:'1920 1080', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter width & height, e.g. "1920 1080"'; let [w,h]=n.map(x=>Math.round(x)); if(!w||!h) return 'Both must be non-zero'; const g=(a,b)=>b?g(b,a%b):a; const d=g(w,h); return `${w}×${h} → ${w/d}:${h/d}`; } },
  { id:'std-dev', name:'Standard Deviation', emoji:'📉', cat:'Calc', desc:'Mean, variance & std deviation.', placeholder:'e.g. 4, 8, 15, 16, 23', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter at least two numbers'; const m=n.reduce((a,b)=>a+b,0)/n.length; const v=n.reduce((a,b)=>a+(b-m)*(b-m),0)/n.length; return `Mean: ${m.toFixed(3)}\nVariance: ${v.toFixed(3)}\nStd Dev: ${Math.sqrt(v).toFixed(3)}`; } },

  // ---- Time (2) ----
  { id:'unix-time', name:'Unix ↔ Date', emoji:'🕰️', cat:'Time', desc:'Convert a Unix timestamp to a date.', placeholder:'e.g. 1751000000', run:s=>{ const t=parseInt(s,10); if(isNaN(t)) return 'Enter a Unix timestamp (seconds)'; const d=new Date(t*1000); if(isNaN(d)) return 'Invalid timestamp'; return d.toUTCString()+'\n(local: '+d.toLocaleString()+')'; } },
  { id:'add-days', name:'Add Days to Date', emoji:'📆', cat:'Time', desc:'Date + N days — "2026-01-01 + 30".', placeholder:'2026-01-01 + 30', run:s=>{ const dm=s.match(/\d{4}-\d{1,2}-\d{1,2}/); if(!dm) return 'Format: 2026-01-01 + 30 (or - 30)'; const d=parseDate(dm[0]); if(!d) return 'Bad date'; const nm=s.slice(dm.index+dm[0].length).match(/([+-])?\s*(\d+)/); const n=nm?(nm[1]==='-'?-1:1)*parseInt(nm[2],10):0; d.setDate(d.getDate()+n); return d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'}); } },

  // ---- Color (2) ----
  { id:'lighten-color', name:'Lighten / Darken', emoji:'🌓', cat:'Color', desc:'Shift a hex color — "#hex +20".', placeholder:'#4f8cff +20', run:s=>{ const hm=(s.match(/#?[0-9a-f]{3,6}/i)||[])[0]; const pm=(s.match(/[+-]?\d+(?!\w)/g)||[]); const r=hexToRgb(hm||''); if(!r) return 'Format: #4f8cff +20 (or -20 to darken)'; const amt=Math.round(255*((pm.length?+pm[pm.length-1]:20)/100)); const c='#'+r.map(v=>toHex2(v+amt)).join(''); return c.toUpperCase(); } },
  { id:'contrast-checker', name:'Contrast Checker', emoji:'🌗', cat:'Color', desc:'WCAG contrast of two hex colors.', placeholder:'#ffffff #6a1b9a', run:s=>{ const hs=s.match(/#?[0-9a-f]{6}/gi); if(!hs||hs.length<2) return 'Enter two hex colors, e.g. "#ffffff #6a1b9a"'; const a=hexToRgb(hs[0]), b=hexToRgb(hs[1]); if(!a||!b) return 'Invalid colors'; const l1=relLum(...a), l2=relLum(...b); const ratio=(Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05); const grade=ratio>=7?'AAA ✅':ratio>=4.5?'AA ✅':ratio>=3?'AA Large ⚠️':'Fail ❌'; return `Contrast: ${ratio.toFixed(2)}:1\nRating: ${grade}`; } },

  // ---- Random (3) ----
  { id:'dice-notation', name:'Dice Roller (2d6)', emoji:'🎲', cat:'Random', desc:'Roll RPG dice — "2d6", "1d20", "3d8+2".', placeholder:'e.g. 2d6+1', gen:true, run:s=>{ const m=(s||'1d6').trim().match(/^(\d*)d(\d+)([+-]\d+)?$/i); if(!m) return 'Format: 2d6, 1d20, 3d8+2'; const count=Math.min(+(m[1]||1),100), sides=+m[2], mod=m[3]?+m[3]:0; if(sides<1) return 'Sides must be ≥ 1'; const rolls=Array.from({length:count},()=>1+Math.floor(Math.random()*sides)); const sum=rolls.reduce((a,b)=>a+b,0)+mod; return `🎲 [${rolls.join(', ')}]${mod?(mod>0?' +'+mod:' '+mod):''} = ${sum}`; } },
  { id:'random-quote', name:'Random Quote', emoji:'💬', cat:'Random', desc:'A little dose of inspiration.', gen:true, run:()=>pick(['“The best way to get started is to quit talking and begin doing.” — Walt Disney','“Dream big and dare to fail.” — Norman Vaughan','“It always seems impossible until it’s done.” — Nelson Mandela','“Little by little, one travels far.” — J.R.R. Tolkien','“Believe you can and you’re halfway there.” — T. Roosevelt','“Stay hungry, stay foolish.” — Steve Jobs','“Whatever you are, be a good one.” — Abraham Lincoln','“Creativity is intelligence having fun.” — Albert Einstein']) },
  { id:'random-card', name:'Draw a Card', emoji:'🃏', cat:'Random', desc:'Draw a random playing card.', gen:true, run:()=>{ const r=['A','2','3','4','5','6','7','8','9','10','J','Q','K'], suits=['♠️','♥️','♦️','♣️']; return pick(r)+pick(suits); } },

  // ================= 25 MORE TOOLS (now 150) =================
  // ---- Text (5) ----
  { id:'unique-words', name:'Count Unique Words', emoji:'🔢', cat:'Text', desc:'How many different words are used.', run:s=>{ const w=(s.toLowerCase().match(/[a-z0-9']+/g)||[]); return w.length?`Total words: ${w.length}\nUnique words: ${new Set(w).size}`:'Enter some text'; } },
  { id:'remove-dup-words', name:'Remove Duplicate Words', emoji:'🧹', cat:'Text', desc:'Keep the first of each repeated word.', run:s=>{ const seen=new Set(); return s.split(/(\s+)/).filter(t=>{ if(/^\s*$/.test(t)) return true; const k=t.toLowerCase().replace(/[^a-z0-9']/g,''); if(!k) return true; if(seen.has(k)) return false; seen.add(k); return true; }).join('').replace(/[ \t]{2,}/g,' ').replace(/ +\n/g,'\n').trim(); } },
  { id:'longest-line', name:'Longest Line', emoji:'📐', cat:'Text', desc:'Find the longest line in your text.', run:s=>{ const L=s.split('\n'); if(!L.length) return 'No lines'; const m=L.reduce((a,b)=>b.length>a.length?b:a); return `Line ${L.indexOf(m)+1} (${m.length} chars):\n${m}`; } },
  { id:'avg-word-length', name:'Average Word Length', emoji:'📊', cat:'Text', desc:'Mean letters per word.', run:s=>{ const w=(s.match(/[A-Za-z']+/g)||[]); if(!w.length) return 'Enter some words'; const avg=w.reduce((a,b)=>a+b.length,0)/w.length; return `${w.length} words\nAverage length: ${avg.toFixed(2)} letters`; } },
  { id:'extract-phone', name:'Extract Phone Numbers', emoji:'📞', cat:'Text', desc:'Pull phone numbers out of text.', run:s=>{ const m=s.match(/\+?\d[\d\s().-]{6,}\d/g); return m?[...new Set(m.map(x=>x.trim()))].join('\n'):'No phone numbers found'; } },
  // ---- Format (3) ----
  { id:'reverse-lines', name:'Reverse Line Order', emoji:'🔃', cat:'Format', desc:'Flip the order of the lines.', run:s=>s.split('\n').reverse().join('\n') },
  { id:'sort-lines-desc', name:'Sort Lines Z→A', emoji:'🔡', cat:'Format', desc:'Sort each line reverse-alphabetically.', run:s=>s.split('\n').sort((a,b)=>b.localeCompare(a)).join('\n') },
  { id:'smart-title', name:'Smart Title Case', emoji:'🎩', cat:'Format', desc:'Title case that keeps small words lower.', run:s=>{ const small=new Set(['a','an','the','and','but','or','for','nor','of','on','in','to','by','at','as','with']); const w=s.toLowerCase().trim().split(/\s+/); return w.map((x,i)=>(i>0&&i<w.length-1&&small.has(x))?x:x.charAt(0).toUpperCase()+x.slice(1)).join(' '); } },
  // ---- Encode (3) ----
  { id:'base64url', name:'Base64 URL-safe', emoji:'🔗', cat:'Encode', desc:'URL-safe Base64 (- and _).', run:s=>{ try{ return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }catch(e){ return 'Could not encode'; } } },
  { id:'rot18', name:'ROT18', emoji:'🔁', cat:'Encode', desc:'ROT13 for letters + ROT5 for digits.', run:s=>s.replace(/[a-z]/gi,c=>{ const b=c<='Z'?65:97; return String.fromCharCode((c.charCodeAt(0)-b+13)%26+b); }).replace(/[0-9]/g,d=>String((+d+5)%10)) },
  { id:'caesar-decode', name:'Caesar Decode (-3)', emoji:'🏺', cat:'Encode', desc:'Shift each letter back by 3.', run:s=>s.replace(/[a-z]/gi,c=>{ const b=c<='Z'?65:97; return String.fromCharCode((c.charCodeAt(0)-b+23)%26+b); }) },
  // ---- Calc (6) ----
  { id:'simple-interest', name:'Simple Interest', emoji:'💵', cat:'Calc', desc:'I = P·R·T — "principal rate% years".', placeholder:'1000 5 3', run:s=>{ const n=nums(s); if(n.length<3) return 'Enter principal, rate%, years'; const p=n[0],r=n[1],t=n[2]; const i=p*r*t/100; return `Interest: ${i.toFixed(2)}\nTotal: ${(p+i).toFixed(2)}`; } },
  { id:'circle-area', name:'Circle Area', emoji:'⭕', cat:'Calc', desc:'Area & circumference from radius.', placeholder:'e.g. 5', run:s=>{ const r=parseFloat(s); if(isNaN(r)||r<0) return 'Enter a radius'; return `Area: ${(Math.PI*r*r).toFixed(3)}\nCircumference: ${(2*Math.PI*r).toFixed(3)}`; } },
  { id:'area-perimeter', name:'Rectangle Area', emoji:'⬛', cat:'Calc', desc:'Area & perimeter — "width height".', placeholder:'e.g. 8 5', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter width & height'; const w=n[0],h=n[1]; return `Area: ${w*h}\nPerimeter: ${2*(w+h)}`; } },
  { id:'speed-calc', name:'Speed Calculator', emoji:'🏎️', cat:'Calc', desc:'Speed = distance ÷ time.', placeholder:'distance time  e.g. 150 3', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter distance & time'; const d=n[0],t=n[1]; if(t===0) return 'Time can’t be 0'; return `Speed: ${(d/t).toFixed(2)} units/time`; } },
  { id:'fraction-decimal', name:'Fraction → Decimal', emoji:'➗', cat:'Calc', desc:'Convert a/b to a decimal.', placeholder:'e.g. 3/8', run:s=>{ const m=s.match(/(-?\d+(?:\.\d+)?)\s*\/\s*(-?\d+(?:\.\d+)?)/); if(!m) return 'Format: 3/8'; const b=+m[2]; if(b===0) return 'Denominator can’t be 0'; return `${m[1]}/${m[2]} = ${(+m[1]/b)}`; } },
  { id:'scientific-notation', name:'Scientific Notation', emoji:'🔬', cat:'Calc', desc:'Write a number as a×10ⁿ.', placeholder:'e.g. 149600000', run:s=>{ const n=parseFloat(s); if(isNaN(n)) return 'Enter a number'; if(n===0) return '0'; return n.toExponential(4).replace(/e\+?(-?\d+)/,' × 10^$1'); } },
  // ---- Time (3) ----
  { id:'leap-year', name:'Leap Year Checker', emoji:'📅', cat:'Time', desc:'Is a year a leap year?', placeholder:'e.g. 2024', run:s=>{ const y=parseInt(s,10); if(isNaN(y)) return 'Enter a year'; const leap=(y%4===0&&y%100!==0)||y%400===0; return `${y} is ${leap?'a LEAP year 🐸 (366 days)':'not a leap year (365 days)'}`; } },
  { id:'zodiac-sign', name:'Zodiac Sign', emoji:'♈', cat:'Time', desc:'Find the star sign for a birthday.', placeholder:'e.g. 2010-08-14', run:s=>{ const d=parseDate(s); if(!d) return 'Enter a date, e.g. 2010-08-14'; return 'Your sign: '+zodiac(d.getMonth()+1,d.getDate()); } },
  { id:'hours-breakdown', name:'Hours → Days', emoji:'⏳', cat:'Time', desc:'Break hours into days, hours & minutes.', placeholder:'e.g. 100', run:s=>{ const h=parseFloat(s); if(isNaN(h)||h<0) return 'Enter a number of hours'; const total=Math.round(h*60); const d=Math.floor(total/1440), hh=Math.floor(total/60)%24, mm=total%60; return `${h} hours = ${d}d ${hh}h ${mm}m`; } },
  // ---- Color (2) ----
  { id:'hex-to-hsl', name:'HEX → HSL', emoji:'🎨', cat:'Color', desc:'Convert a hex color to HSL.', placeholder:'#4f8cff', run:s=>{ const r=hexToRgb(s); if(!r) return 'Enter a hex color like #4f8cff'; const h=rgbToHsl(r[0],r[1],r[2]); return `hsl(${h[0]}, ${h[1]}%, ${h[2]}%)`; } },
  { id:'color-mixer', name:'Mix Two Colors', emoji:'🖌️', cat:'Color', desc:'Blend two hex colors 50/50.', placeholder:'#ff0000 #0000ff', run:s=>{ const hs=s.match(/#?[0-9a-f]{6}/gi); if(!hs||hs.length<2) return 'Enter two hex colors'; const a=hexToRgb(hs[0]),b=hexToRgb(hs[1]); if(!a||!b) return 'Invalid colors'; const mix='#'+a.map((v,i)=>toHex2((v+b[i])/2)).join(''); return `Mixed: ${mix.toUpperCase()}`; } },
  // ---- Random (3) ----
  { id:'flip-coins', name:'Flip N Coins', emoji:'🪙', cat:'Random', desc:'Flip several coins at once.', placeholder:'e.g. 10', run:s=>{ let n=parseInt(s,10); if(isNaN(n)||n<1)n=5; n=Math.min(n,100); let heads=0; const r=Array.from({length:n},()=>{ const hd=Math.random()<0.5; if(hd)heads++; return hd?'H':'T'; }); return r.join(' ')+`\n\nHeads: ${heads}  Tails: ${n-heads}`; } },
  { id:'password-gen', name:'Password Generator', emoji:'🔐', cat:'Random', desc:'Strong random password (type a length).', placeholder:'e.g. 16', run:s=>{ let n=parseInt(s,10); if(isNaN(n)||n<4)n=16; n=Math.min(n,64); const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*'; let p=''; for(let i=0;i<n;i++) p+=c[Math.floor(Math.random()*c.length)]; return p; } },
  { id:'team-name-gen', name:'Team Name Generator', emoji:'🏆', cat:'Random', desc:'A punchy random team name.', gen:true, run:()=>{ const a=['Thunder','Cosmic','Savage','Golden','Shadow','Turbo','Mighty','Electric','Wild','Royal','Frost','Blazing']; const b=['Tigers','Dragons','Wolves','Titans','Falcons','Sharks','Ninjas','Phoenix','Vipers','Raptors','Comets','Legends']; return pick(a)+' '+pick(b); } },

  // ================= 15 MORE TOOLS (now 165) =================
  // ---- Text (4) ----
  { id:'syllable-count', name:'Syllable Counter', emoji:'🗣️', cat:'Text', desc:'Estimate the syllables in your text.', run:s=>{ const w=(s.toLowerCase().match(/[a-z]+/g)||[]); if(!w.length) return 'Enter some words'; const syl=x=>{ x=x.replace(/e$/,''); const m=x.match(/[aeiouy]+/g); return Math.max(1,m?m.length:1); }; const total=w.reduce((a,b)=>a+syl(b),0); return `${w.length} words\n~${total} syllables`; } },
  { id:'char-frequency', name:'Letter Frequency', emoji:'📊', cat:'Text', desc:'Your most-used letters.', run:s=>{ const c=(s.toLowerCase().match(/[a-z]/g)||[]); if(!c.length) return 'Enter some letters'; const f={}; c.forEach(x=>f[x]=(f[x]||0)+1); return Object.entries(f).sort((a,b)=>b[1]-a[1]).slice(0,8).map(e=>`${e[0]}: ${e[1]}`).join('\n'); } },
  { id:'remove-vowels', name:'Remove Vowels', emoji:'🚫', cat:'Text', desc:'Strip out every vowel.', run:s=>s.replace(/[aeiou]/gi,'') },
  { id:'keep-vowels', name:'Keep Only Vowels', emoji:'🅰️', cat:'Text', desc:'Remove every consonant.', run:s=>s.replace(/[bcdfghjklmnpqrstvwxyz]/gi,'') },
  // ---- Format (3) ----
  { id:'calm-caps', name:'Calm the Caps', emoji:'😌', cat:'Format', desc:'Turn SHOUTY all-caps words into normal ones.', run:s=>s.replace(/\b[A-Z]{2,}\b/g, w=>w.charAt(0)+w.slice(1).toLowerCase()) },
  { id:'dot-case', name:'dot.case', emoji:'🔵', cat:'Format', desc:'join.words.with.dots', run:s=>words(s).map(w=>w.toLowerCase()).join('.') },
  { id:'train-case', name:'Train-Case', emoji:'🚂', cat:'Format', desc:'Join-Words-With-Hyphens-Capitalized.', run:s=>words(s).map(w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join('-') },
  // ---- Encode (3) ----
  { id:'a1z26', name:'A1Z26 Cipher', emoji:'🔢', cat:'Encode', desc:'Turn letters into numbers (a=1 … z=26).', run:s=>s.toUpperCase().replace(/[^A-Z ]/g,'').split('').map(c=>c===' '?'/':(c.charCodeAt(0)-64)).join('-') },
  { id:'a1z26-decode', name:'A1Z26 Decode', emoji:'🔡', cat:'Encode', desc:'Turn A1Z26 numbers back into letters.', placeholder:'8-9 / 20-8-5-18-5', run:s=>s.trim().split(/[-\s]+/).map(t=>{ if(t==='/') return ' '; const n=parseInt(t,10); return (n>=1&&n<=26)?String.fromCharCode(64+n):''; }).join('') },
  { id:'regional-flags', name:'🇦🇧 Flag Letters', emoji:'🏴', cat:'Encode', desc:'Turn letters into regional-indicator symbols.', run:s=>Array.from(s.toUpperCase()).map(c=>(c>='A'&&c<='Z')?String.fromCodePoint(0x1F1E6+c.charCodeAt(0)-65):c).join('') },
  // ---- Calc (3) ----
  { id:'tax-calc', name:'Tax / GST Calculator', emoji:'🧾', cat:'Calc', desc:'Add a percentage tax to an amount.', placeholder:'amount rate%  e.g. 60 18', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter amount & rate%, e.g. "60 18"'; const a=n[0],r=n[1]; const tax=a*r/100; return `Tax: ${tax.toFixed(2)}\nTotal: ${(a+tax).toFixed(2)}`; } },
  { id:'tip-split', name:'Split the Bill', emoji:'💸', cat:'Calc', desc:'Bill + people (+ tip%) → each pays.', placeholder:'bill people tip%  e.g. 80 4 15', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter bill & people, e.g. "80 4 15"'; const bill=n[0], people=Math.max(1,Math.round(n[1])), tip=n.length>2?n[2]:15; const total=bill*(1+tip/100); return `${tip}% tip → total $${total.toFixed(2)}\nEach of ${people} pays $${(total/people).toFixed(2)}`; } },
  { id:'dog-years', name:'Dog Years 🐶', emoji:'🐶', cat:'Calc', desc:'Convert human years to dog years.', placeholder:'e.g. 5', run:s=>{ const y=parseFloat(s); if(isNaN(y)||y<0) return 'Enter an age in human years'; let d = y<=2 ? y*10.5 : 21+(y-2)*4; return `${y} human years ≈ ${Math.round(d)} dog years 🐶`; } },
  // ---- Time (1) ----
  { id:'day-of-year', name:'Day of the Year', emoji:'📅', cat:'Time', desc:'Which numbered day of the year is a date?', placeholder:'e.g. 2026-07-08', run:s=>{ const dt=parseDate(s); if(!dt) return 'Enter a date, e.g. 2026-07-08'; const start=new Date(dt.getFullYear(),0,0); const day=Math.floor((dt-start)/86400000); return `${dt.getFullYear()} — day ${day} of the year`; } },
  { id:'tally-marks', name:'Tally Marks', emoji:'✒️', cat:'Fun', desc:'Turn a number into tally marks.', placeholder:'e.g. 12', run:s=>{ const n=parseInt(s,10); if(isNaN(n)||n<0) return 'Enter a whole number ≥ 0'; if(n>1000) return 'Keep it ≤ 1000'; if(n===0) return '0'; let out=[],r=n; while(r>=5){ out.push('卌'); r-=5; } if(r>0) out.push('|'.repeat(r)); return out.join(' '); } },

  // ================= 15 MORE TOOLS (now 180) =================
  // ---- Text (5) ----
  { id:'remove-emojis', name:'Remove Emojis', emoji:'🚫', cat:'Text', desc:'Strip all emojis out of your text.', run:s=>{ const r=s.replace(/[\p{Extended_Pictographic}️‍]/gu,'').replace(/[ \t]{2,}/g,' '); return r.trim()||'(no text left)'; } },
  { id:'count-emojis', name:'Count Emojis', emoji:'😀', cat:'Text', desc:'Count the emojis in your text.', run:s=>{ const m=s.match(/\p{Extended_Pictographic}/gu); return m?`${m.length} emoji${m.length===1?'':'s'}: ${[...new Set(m)].join(' ')}`:'No emojis found'; } },
  { id:'palindrome-check', name:'Palindrome Checker', emoji:'🔁', cat:'Text', desc:'Reads the same forwards and backwards?', placeholder:'e.g. racecar', run:s=>{ const c=s.toLowerCase().replace(/[^a-z0-9]/g,''); if(!c) return 'Enter some text'; return c===c.split('').reverse().join('') ? `✅ Yes — “${s.trim()}” is a palindrome!` : '❌ Not a palindrome.'; } },
  { id:'pangram-check', name:'Pangram Checker', emoji:'🅰️', cat:'Text', desc:'Does it use all 26 letters?', placeholder:'The quick brown fox…', run:s=>{ const set=new Set(s.toLowerCase().replace(/[^a-z]/g,'')); return set.size>=26 ? '✅ Yes — a pangram! (all 26 letters)' : `Not a pangram — missing ${26-set.size} letter${26-set.size===1?'':'s'}.`; } },
  { id:'anagram-check', name:'Anagram Checker', emoji:'🔀', cat:'Text', desc:'Are two words anagrams?', placeholder:'listen | silent', run:s=>{ const w=(s.toLowerCase().match(/[a-z0-9]+/g)||[]); if(w.length<2) return 'Enter two words, e.g. "listen | silent"'; const n=x=>x.split('').sort().join(''); return n(w[0])===n(w[1]) ? `✅ Yes — “${w[0]}” and “${w[1]}” are anagrams!` : `❌ “${w[0]}” and “${w[1]}” are not anagrams.`; } },
  // ---- Format (3) ----
  { id:'underscore-spaces', name:'Spaces → Underscores', emoji:'➖', cat:'Format', desc:'Replace spaces with underscores.', run:s=>s.replace(/ /g,'_') },
  { id:'wrap-quotes', name:'Quote Each Line', emoji:'❝', cat:'Format', desc:'Wrap every line in quotation marks.', run:s=>s.split('\n').map(l=>'"'+l+'"').join('\n') },
  { id:'hashtagify', name:'Make a #Hashtag', emoji:'#️⃣', cat:'Format', desc:'Turn a phrase into one #Hashtag.', placeholder:'throwback thursday', run:s=>{ const w=words(s); return w.length ? '#'+w.map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join('') : 'Enter some words'; } },
  // ---- Calc (4) ----
  { id:'even-odd', name:'Even or Odd?', emoji:'⚖️', cat:'Calc', desc:'Is a number even or odd?', placeholder:'e.g. 42', run:s=>{ const n=parseInt(s,10); if(isNaN(n)) return 'Enter a whole number'; return `${n} is ${Math.abs(n)%2===0?'EVEN':'ODD'}`; } },
  { id:'power', name:'Power (xʸ)', emoji:'🔺', cat:'Calc', desc:'Raise a number to a power.', placeholder:'base exponent  e.g. 2 10', run:s=>{ const n=nums(s); if(n.length<2) return 'Enter base & exponent, e.g. "2 10"'; return `${n[0]}^${n[1]} = ${Math.pow(n[0],n[1])}`; } },
  { id:'ordinal-number', name:'Ordinal (1st, 2nd…)', emoji:'🥇', cat:'Calc', desc:'Turn a number into its ordinal.', placeholder:'e.g. 23', run:s=>{ const n=parseInt(s,10); if(isNaN(n)) return 'Enter a whole number'; const a=Math.abs(n)%100,b=Math.abs(n)%10; const suf=(a>=11&&a<=13)?'th':b===1?'st':b===2?'nd':b===3?'rd':'th'; return n+suf; } },
  { id:'factors', name:'Factor Finder', emoji:'🧮', cat:'Calc', desc:'List all the factors of a number.', placeholder:'e.g. 60', run:s=>{ const n=parseInt(s,10); if(isNaN(n)||n<1) return 'Enter a whole number ≥ 1'; if(n>1000000) return 'Keep it ≤ 1,000,000'; const f=[]; for(let i=1;i*i<=n;i++){ if(n%i===0){ f.push(i); if(i!==n/i) f.push(n/i); } } f.sort((a,b)=>a-b); return `Factors of ${n}:\n${f.join(', ')}\n(${f.length} total)`; } },
  // ---- Fun (2) ----
  { id:'rock-paper-scissors', name:'Rock Paper Scissors', emoji:'✊', cat:'Fun', desc:'Mochi throws one — can you beat it?', gen:true, run:()=>'I throw… '+pick(['🪨 Rock','📄 Paper','✂️ Scissors'])+'!' },
  { id:'would-you-rather', name:'Would You Rather', emoji:'🤔', cat:'Fun', desc:'A fun this-or-that to ponder.', gen:true, run:()=>pick(['Would you rather be able to fly 🕊️ or be invisible 👻?','Would you rather have a pet dragon 🐉 or a pet unicorn 🦄?','Would you rather never eat pizza 🍕 again or never eat ice cream 🍦 again?','Would you rather explore space 🚀 or the deep ocean 🌊?','Would you rather be super strong 💪 or super fast ⚡?','Would you rather live in a treehouse 🌳 or a castle 🏰?','Would you rather talk to animals 🐾 or speak every language 🗣️?','Would you rather have endless summer ☀️ or endless winter ❄️?']) },
  // ---- Random (1) ----
  { id:'random-username', name:'Username Generator', emoji:'🏷️', cat:'Random', desc:'A cool random username idea.', gen:true, run:()=>{ const a=['Cosmic','Pixel','Turbo','Ninja','Mega','Silent','Golden','Neon','Frost','Lucky','Shadow','Swift']; const n=['Panda','Falcon','Tiger','Wizard','Comet','Fox','Dragon','Otter','Raccoon','Phoenix','Wolf','Koala']; return '@'+pick(a)+pick(n)+(Math.floor(Math.random()*90)+10); } },

  // ================= 20 MORE TOOLS (now 200) =================
  // ---- Text (6) ----
  { id:'count-sentences', name:'Sentence Counter', emoji:'🔢', cat:'Text', desc:'Count sentences and words.', run:s=>{ const w=(s.trim().match(/\S+/g)||[]).length; if(!w) return 'Enter some text'; const n=(s.match(/[.!?]+(\s|$)/g)||[]).length; return `${Math.max(n,1)} sentence${Math.max(n,1)===1?'':'s'}, ${w} words`; } },
  { id:'reverse-word-order', name:'Reverse Word Order', emoji:'↔️', cat:'Text', desc:'Flip the order of the words.', run:s=>s.trim().split(/\s+/).filter(Boolean).reverse().join(' ') },
  { id:'sort-words', name:'Sort Words A–Z', emoji:'🔤', cat:'Text', desc:'Alphabetise the words.', run:s=>{ const w=s.trim().split(/\s+/).filter(Boolean); if(!w.length) return 'Enter some words'; return w.sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase())).join(' '); } },
  { id:'shuffle-words', name:'Shuffle Words', emoji:'🔀', cat:'Text', desc:'Randomly reorder the words.', run:s=>{ const w=s.trim().split(/\s+/).filter(Boolean); if(!w.length) return 'Enter some words'; for(let i=w.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); const t=w[i];w[i]=w[j];w[j]=t; } return w.join(' '); } },
  { id:'swap-case', name:'Swap Case', emoji:'🔃', cat:'Text', desc:'Flip UPPER ↔ lower on every letter.', run:s=>s.replace(/[a-zA-Z]/g,c=>c===c.toLowerCase()?c.toUpperCase():c.toLowerCase()) },
  { id:'count-paragraphs', name:'Paragraph Counter', emoji:'¶', cat:'Text', desc:'Count the paragraphs (blank-line separated).', run:s=>{ const p=s.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean); return `${p.length} paragraph${p.length===1?'':'s'}`; } },
  // ---- Format (3) ----
  { id:'remove-line-breaks', name:'Remove Line Breaks', emoji:'➡️', cat:'Format', desc:'Join everything onto one line.', run:s=>s.replace(/\s*\n\s*/g,' ').trim() },
  { id:'add-bullets', name:'Add Bullet Points', emoji:'•', cat:'Format', desc:'Turn each line into a bullet.', run:s=>{ const l=s.split('\n').map(x=>x.trim()).filter(Boolean); return l.length?l.map(x=>'• '+x).join('\n'):'Enter some lines'; } },
  { id:'indent-lines', name:'Indent Lines', emoji:'⇥', cat:'Format', desc:'Add 4 spaces before each line.', run:s=>s.split('\n').map(l=>'    '+l).join('\n') },
  // ---- Calc (5) ----
  { id:'median', name:'Median', emoji:'📊', cat:'Calc', desc:'The middle value of your numbers.', placeholder:'e.g. 3 1 4 1 5', run:s=>{ const n=nums(s); if(!n.length) return 'Enter numbers, e.g. "3 1 4 1 5"'; const a=n.slice().sort((x,y)=>x-y); const m=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2; return 'Median: '+m; } },
  { id:'average', name:'Average (Mean)', emoji:'➗', cat:'Calc', desc:'The average of your numbers.', placeholder:'e.g. 10 20 30', run:s=>{ const n=nums(s); if(!n.length) return 'Enter numbers'; return 'Average: '+(Math.round((n.reduce((a,b)=>a+b,0)/n.length)*10000)/10000); } },
  { id:'sum', name:'Sum', emoji:'➕', cat:'Calc', desc:'Add up all the numbers.', placeholder:'e.g. 5 10 15', run:s=>{ const n=nums(s); if(!n.length) return 'Enter numbers'; return 'Sum: '+n.reduce((a,b)=>a+b,0); } },
  { id:'product', name:'Product (Multiply)', emoji:'✖️', cat:'Calc', desc:'Multiply all the numbers together.', placeholder:'e.g. 2 3 4', run:s=>{ const n=nums(s); if(!n.length) return 'Enter numbers'; return 'Product: '+n.reduce((a,b)=>a*b,1); } },
  { id:'number-range', name:'Min · Max · Range', emoji:'📈', cat:'Calc', desc:'Smallest, largest and the spread.', placeholder:'e.g. 7 2 9 4', run:s=>{ const n=nums(s); if(!n.length) return 'Enter numbers'; const mn=Math.min.apply(null,n), mx=Math.max.apply(null,n); return `Min: ${mn}\nMax: ${mx}\nRange: ${mx-mn}`; } },
  // ---- Fun (6) ----
  { id:'fortune-cookie', name:'Fortune Cookie', emoji:'🥠', cat:'Fun', desc:'Crack open a little fortune.', gen:true, run:()=>'🥠 '+pick(['A pleasant surprise is waiting for you.','Your kindness will lead you somewhere wonderful.','Adventure is on your horizon.','A small step today becomes a giant leap tomorrow.','The answer you seek is closer than you think.','Good news will reach you soon.','Someone is thinking of you right now.','Your creativity will open a new door.','Now is a good time to make a new friend.','Trust your gut — it knows the way.']) },
  { id:'dad-joke', name:'Dad Joke', emoji:'👨', cat:'Fun', desc:'A groan-worthy dad joke.', gen:true, run:()=>pick(["Why don't skeletons fight each other? They don't have the guts. 💀","I only know 25 letters of the alphabet. I don't know y. 🔤","What do you call fake spaghetti? An impasta! 🍝","Why did the scarecrow win an award? He was outstanding in his field. 🌾","I used to hate facial hair… but then it grew on me. 🧔","What do you call cheese that isn't yours? Nacho cheese! 🧀","I'm reading a book about anti-gravity — it's impossible to put down! 📖","Why can't your nose be 12 inches long? Then it'd be a foot. 👃"]) },
  { id:'compliment', name:'Compliment', emoji:'🌟', cat:'Fun', desc:'A little pick-me-up.', gen:true, run:()=>pick(["You're doing better than you think. 🌟","Your smile is contagious. 😊","You bring out the best in people. 💛","You're braver than you believe. 🦁","The world is better with you in it. 🌍","You have great taste — you're here, after all! ✨","You're capable of amazing things. 🚀","Your kindness makes a real difference. 💜"]) },
  { id:'random-fact', name:'Random Fact', emoji:'🤓', cat:'Fun', desc:'A surprising true fact.', gen:true, run:()=>'🤓 '+pick(['Honey never spoils — 3,000-year-old honey is still edible.','Octopuses have three hearts and blue blood.','A group of flamingos is called a "flamboyance".','Bananas are berries, but strawberries are not.','Wombat poop is cube-shaped.','The Eiffel Tower can grow over 15 cm taller in summer.','Sharks are older than trees.','A day on Venus is longer than its year.','Sea otters hold hands while sleeping so they do not drift apart.','Cows have best friends.']) },
  { id:'truth-or-dare', name:'Truth or Dare', emoji:'🎯', cat:'Fun', desc:'Get a random truth or dare.', gen:true, run:()=> (Math.random()<0.5 ? 'Truth: '+pick(["What's your most-used emoji?","What's a talent you wish you had?","What's your favourite way to spend a weekend?","What's the best gift you've ever received?","If you could visit anywhere, where would you go?"]) : 'Dare: '+pick(['Talk in an accent for 5 minutes.','Do your best animal impression.','Text a friend a random compliment.','Sing the chorus of your favourite song.','Do 10 star jumps right now.'])) },
  { id:'spirit-animal', name:'Spirit Animal', emoji:'🦊', cat:'Fun', desc:'Discover your spirit animal.', gen:true, run:()=>'Your spirit animal is… '+pick(['🦊 the clever Fox','🦉 the wise Owl','🐬 the playful Dolphin','🐺 the loyal Wolf','🦁 the brave Lion','🐢 the patient Turtle','🦋 the free Butterfly','🐧 the cheerful Penguin','🐈 the curious Cat','🐝 the busy Bee']) },

  // ---- 3 more (203) ----
  { id:'days-until', name:'Days Until a Date', emoji:'📆', cat:'Time', desc:'Count the days until (or since) a date.', placeholder:'e.g. 2026-12-25', run:s=>{ const dt=parseDate(s); if(!dt) return 'Enter a date, e.g. 2026-12-25'; const t=new Date(); t.setHours(0,0,0,0); const d=Math.round((dt-t)/86400000); if(d===0) return "That's today! 🎉"; return d>0 ? `${d} day${d===1?'':'s'} to go 📅` : `${Math.abs(d)} day${Math.abs(d)===1?'':'s'} ago`; } },
  { id:'strikethrough-text', name:'Strikethrough Text', emoji:'🚫', cat:'Format', desc:'A̶d̶d̶ ̶a̶ ̶l̶i̶n̶e̶ ̶t̶h̶r̶o̶u̶g̶h̶ your text.', run:s=>Array.from(s).map(c=>c+'̶').join('') },
  { id:'prime-factors', name:'Prime Factors', emoji:'🔢', cat:'Calc', desc:'Break a number into its prime factors.', placeholder:'e.g. 360', run:s=>{ let n=parseInt(s,10); if(isNaN(n)||n<2) return 'Enter a whole number ≥ 2'; if(n>1e12) return 'Keep it ≤ 1,000,000,000,000'; const orig=n, f=[]; for(let d=2;d*d<=n;d++){ while(n%d===0){ f.push(d); n=n/d; } } if(n>1) f.push(n); return `${orig} = ${f.join(' × ')}`; } },
];

/* ============================================================
   Programmatically-generated functional tool families.
   These push additional *working* tools into TOOLS at load time — keeping this
   source file small while giving a large toolbox. Every one genuinely computes
   a result; the hand-curated tools above stay first in the list.
   ============================================================ */
(function generateTools(){
  const num = fn => s => { const x = parseFloat(s); return isNaN(x) ? 'Enter a number' : String(fn(x)); };
  const r6 = x => Math.round(x * 1e6) / 1e6;
  // Times tables (1..100)
  for(let n=1;n<=100;n++) TOOLS.push({ id:'times-table-'+n, name:n+' Times Table', emoji:'✖️', cat:'Math', desc:'The '+n+' times table (×1 to ×12).', gen:true, run:()=>{ let o=''; for(let i=1;i<=12;i++) o+=n+' × '+i+' = '+(n*i)+'\n'; return o.trim(); } });
  // Multiply / Divide by N  (2..2400)
  for(let n=2;n<=2400;n++) TOOLS.push({ id:'multiply-by-'+n, name:'Multiply by '+n, emoji:'✖️', cat:'Math', desc:'Multiply your number by '+n+'.', placeholder:'e.g. 8', run:num(x=>x+' × '+n+' = '+r6(x*n)) });
  for(let n=2;n<=2400;n++) TOOLS.push({ id:'divide-by-'+n, name:'Divide by '+n, emoji:'➗', cat:'Math', desc:'Divide your number by '+n+'.', placeholder:'e.g. 100', run:num(x=>x+' ÷ '+n+' = '+r6(x/n)) });
  // Add / Subtract N  (1..2400)
  for(let n=1;n<=2400;n++) TOOLS.push({ id:'add-num-'+n, name:'Add '+n, emoji:'➕', cat:'Math', desc:'Add '+n+' to your number.', placeholder:'e.g. 50', run:num(x=>x+' + '+n+' = '+r6(x+n)) });
  for(let n=1;n<=2400;n++) TOOLS.push({ id:'subtract-num-'+n, name:'Subtract '+n, emoji:'➖', cat:'Math', desc:'Subtract '+n+' from your number.', placeholder:'e.g. 50', run:num(x=>x+' − '+n+' = '+r6(x-n)) });
  // Percent of N (1..100)
  for(let n=1;n<=100;n++) TOOLS.push({ id:'percent-'+n+'-of', name:n+'% of a Number', emoji:'💯', cat:'Math', desc:'Find '+n+'% of your number.', placeholder:'e.g. 200', run:num(x=>n+'% of '+x+' = '+r6(x*n/100)) });
  // Caesar shifts (1..25)
  for(let n=1;n<=25;n++) TOOLS.push({ id:'caesar-shift-'+n, name:'Caesar Shift +'+n, emoji:'🔐', cat:'Encode', desc:'Shift each letter forward by '+n+' places.', run:s=>String(s).replace(/[a-z]/gi,c=>{ const b=c<='Z'?65:97; return String.fromCharCode((c.charCodeAt(0)-b+n)%26+b); }) });
  // Countdown to Jan 1, YEAR (2027..2126)
  for(let y=2027;y<=2126;y++) TOOLS.push({ id:'days-to-'+y, name:'Days to New Year '+y, emoji:'📆', cat:'Time', desc:'How many days until 1 January '+y+'.', gen:true, run:()=>{ const t=new Date(); t.setHours(0,0,0,0); const d=Math.round((new Date(y,0,1)-t)/86400000); return d>0? d+' days until '+y+' 🎉' : 'That New Year has passed'; } });
  // Round to N decimals (0..15)
  for(let n=0;n<=15;n++) TOOLS.push({ id:'round-'+n+'dp', name:'Round to '+n+' Decimal'+(n===1?'':'s'), emoji:'🔢', cat:'Math', desc:'Round to '+n+' decimal place'+(n===1?'':'s')+'.', placeholder:'e.g. 3.14159', run:num(x=>x.toFixed(n)) });
  // Power of N (2..50)
  for(let n=2;n<=50;n++) TOOLS.push({ id:'power-of-'+n, name:'Raise to Power '+n, emoji:'🔺', cat:'Math', desc:'Raise your number to the power '+n+'.', placeholder:'e.g. 2', run:num(x=>x+'^'+n+' = '+Math.pow(x,n)) });
  // Nth root (2..50)
  for(let n=2;n<=50;n++) TOOLS.push({ id:'nth-root-'+n, name:n+'th Root', emoji:'√', cat:'Math', desc:'The '+n+'th root of your number.', placeholder:'e.g. 64', run:num(x=> (x<0 && n%2===0) ? 'No real '+n+'th root of a negative' : r6(Math.sign(x)*Math.pow(Math.abs(x),1/n)) ) });
  // Repeat text N times (2..100)
  for(let n=2;n<=100;n++) TOOLS.push({ id:'repeat-'+n+'x', name:'Repeat '+n+'×', emoji:'🔁', cat:'Text', desc:'Repeat your text '+n+' times.', run:s=>{ s=String(s).trim(); return s? new Array(n+1).join(s+' ').trim() : 'Enter some text'; } });
  // Decimal → base B (2..36)
  for(let b=2;b<=36;b++) TOOLS.push({ id:'to-base-'+b, name:'Decimal → Base '+b, emoji:'🔟', cat:'Encode', desc:'Convert a whole number to base '+b+'.', placeholder:'e.g. 255', run:s=>{ const x=parseInt(s,10); if(isNaN(x)) return 'Enter a whole number'; return x.toString(b).toUpperCase(); } });
})();
